# Site settings
title: "liuwantao"
email: 13521760670@163.com
name: Liu WanTao
description: "Better Late Than Never"
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: liuwantao
permalink: /:year/:month/:day/:title/

blog_url: www.lwtblog.cn


# Build settings
markdown: kramdown

# highlight
#highlighter: pygments
 highlighter: rouge
# highlighter: false

#背景图
front_img: yes
front_img_path: "static/imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

#头像
avatar: yes
avatar_img_path: "static/imgs/touxiang.jpg"
 

#加载首页邮箱微薄之类的图标
# Delete the lines you don't need
# about 5 elements are recomended
codepen_username: your_codepen_username_goes_here
facebook_username: your_facebook_username_goes_here
vk_username: your_vk_username_goes_here
twitter_username: your_twitter_username_goes_here
google_plus_username: your_google_plus_username_goes_here
linked_in_username: your_linked_in_username_goes_here
vine_username: your_vine_username_goes_here
instagram_username: your_instagram_username_goes_here
flickr_username: your_flickr_username_goes_here
steam_username: your_steam_username_goes_here
soundcloud_username: your_soundcloud_username_goes_here
stack_of_username: your_stack_overflow_account_id_number_goes_here
reddit_username: your_reddit_username_goes_here
medium_username: your_medium_username_goes_here
tumblr_username: your_tumblr_username_goes_here
weibo_username: 3134632731/profile?topnav=1&wvr=6&is_all=1




